import Redis from "ioredis";
import { IDatabaseCacheAdapter, UUID, elizaLogger } from "@elizaos/core";

/**
 * Represents a RedisClient class that implements the IDatabaseCacheAdapter interface.
 */

export class RedisClient implements IDatabaseCacheAdapter {
    private client: Redis;

/**
 * Constructor for initializing a new Redis client.
 * 
 * @param {string} redisUrl - The URL of the Redis server.
 */
    constructor(redisUrl: string) {
        this.client = new Redis(redisUrl);

        this.client.on("connect", () => {
            elizaLogger.success("Connected to Redis");
        });

        this.client.on("error", (err) => {
            elizaLogger.error("Redis error:", err);
        });
    }

/**
 * Asynchronously retrieves a value from the cache based on the provided parameters.
 * 
 * @param {Object} params - The parameters for retrieving the value from cache.
 * @param {UUID} params.agentId - The UUID of the agent.
 * @param {string} params.key - The key used to fetch the value from cache.
 * @returns {Promise<string | undefined>} The cached value or undefined if not found.
 */
    async getCache(params: {
        agentId: UUID;
        key: string;
    }): Promise<string | undefined> {
        try {
            const redisKey = this.buildKey(params.agentId, params.key);
            const value = await this.client.get(redisKey);
            return value || undefined;
        } catch (err) {
            elizaLogger.error("Error getting cache:", err);
            return undefined;
        }
    }

/**
* Asynchronously sets a cache value in Redis for a specified agent using the provided key and value.
* 
* @param {Object} params - The parameters for setting the cache.
* @param {UUID} params.agentId - The unique identifier of the agent.
* @param {string} params.key - The key to be used for storing the value in Redis.
* @param {string} params.value - The value to be stored in Redis.
* @returns {Promise<boolean>} A promise that resolves to a boolean indicating the success of setting the cache value.
*/
```
    async setCache(params: {
        agentId: UUID;
        key: string;
        value: string;
    }): Promise<boolean> {
        try {
            const redisKey = this.buildKey(params.agentId, params.key);
            await this.client.set(redisKey, params.value);
            return true;
        } catch (err) {
            elizaLogger.error("Error setting cache:", err);
            return false;
        }
    }

/**
 * Asynchronously deletes a cache entry based on the provided agentId and key.
 * 
 * @param {Object} params - The parameters for the cache deletion.
 * @param {UUID} params.agentId - The unique identifier of the agent.
 * @param {string} params.key - The key associated with the cache entry to delete.
 * @returns {Promise<boolean>} A Promise that resolves to true if the cache entry was successfully deleted, false otherwise.
 */
    async deleteCache(params: {
        agentId: UUID;
        key: string;
    }): Promise<boolean> {
        try {
            const redisKey = this.buildKey(params.agentId, params.key);
            const result = await this.client.del(redisKey);
            return result > 0;
        } catch (err) {
            elizaLogger.error("Error deleting cache:", err);
            return false;
        }
    }

/**
 * Asynchronously disconnects from Redis.
 * 
 * @returns {Promise<void>} A Promise that resolves when the disconnection is successful.
 */
    async disconnect(): Promise<void> {
        try {
            await this.client.quit();
            elizaLogger.success("Disconnected from Redis");
        } catch (err) {
            elizaLogger.error("Error disconnecting from Redis:", err);
        }
    }

/**
 * Constructs a unique key based on agentId and key
 *
 * @param {UUID} agentId - The unique identifier for the agent
 * @param {string} key - The key to be combined with agentId
 * @returns {string} The unique key generated by combining agentId and key
 */
    private buildKey(agentId: UUID, key: string): string {
        return `${agentId}:${key}`; // Constructs a unique key based on agentId and key
    }
}

export default RedisClient;
